### ISSUE TITLE
windows 提交任务报错

### ISSUE THREAD

**Issue by momisabuilder** [huzekang/springboot-datax#5]
java.io.IOException: Cannot run program "python" (in directory "."): CreateProcess error=2, 系统找不到指定的文件。
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048) ~[na:1.8.0_45]
	at java.lang.Runtime.exec(Runtime.java:620) ~[na:1.8.0_45]
	at org.apache.commons.exec.launcher.Java13CommandLauncher.exec(Java13CommandLauncher.java:61) ~[commons-exec-1.3.jar:1.3]
	at org.apache.commons.exec.DefaultExecutor.launch(DefaultExecutor.java:279) ~[commons-exec-1.3.jar:1.3]
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:336) ~[commons-exec-1.3.jar:1.3]
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166) ~[commons-exec-1.3.jar:1.3]
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:153) ~[commons-exec-1.3.jar:1.3]
	at com.wugui.dataxweb.service.impl.IDataxJobServiceImpl.lambda$startJobByJsonStr$0(IDataxJobServiceImpl.java:80) ~[classes/:na]
	at com.wugui.dataxweb.service.impl.IDataxJobServiceImpl$$Lambda$458/680325159.run(Unknown Source) [classes/:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_45]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [na:1.8.0_45]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [na:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
Caused by: java.io.IOException: CreateProcess error=2, 系统找不到指定的文件。
	at java.lang.ProcessImpl.create(Native Method) ~[na:1.8.0_45]
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:386) ~[na:1.8.0_45]
	at java.lang.ProcessImpl.start(ProcessImpl.java:137) ~[na:1.8.0_45]
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029) ~[na:1.8.0_45]
	... 14 common frames omitted

**Comment by zhouhongfa** [comment]
需要安装python 2.7

**Comment by momisabuilder** [comment]
您好，还有个问题我想咨询下你，我想把datax任务改成定时的，是不是需要进行代码改造？


先建立个任务表，将任务保存起来，然后再进行启动等事项？





------------------ 原始邮件 ------------------
发件人: "zhouhongfa"<notifications@github.com>;
发送时间: 2019年9月5日(星期四) 中午12:25
收件人: "huzekang/springboot-datax"<springboot-datax@noreply.github.com>;
抄送: "烦不烦 "<1518386192@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [huzekang/springboot-datax] windows 提交任务报错 (#5)




需要安装python 2.7

**Comment by zhouhongfa** [comment]
用 `quartz` 吗？在执行器中接收任务id，查询出json，然后直接调用执行任务的方法就可以了

**Comment by momisabuilder** [comment]
你好，字段映射功能尚未实现吗 ？







------------------ 原始邮件 ------------------
发件人: "zhouhongfa"<notifications@github.com>;
发送时间: 2019年9月5日(星期四) 中午1:06
收件人: "huzekang/springboot-datax"<springboot-datax@noreply.github.com>;
抄送: "烦不烦 "<1518386192@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [huzekang/springboot-datax] windows 提交任务报错 (#5)




用 quartz 吗？在执行器中接收任务id，查询出json，然后直接调用执行任务的方法就可以了

**Comment by zhouhongfa** [comment]
@momisabuilder 还没有实现

**Comment by ITriangle** [comment]
对于定时任务，不需要自己开发，可以结合 ariflow 这样的分布式调度开源组件使用 @momisabuilder
